name: WebAuctionPlus
main: com.webauctionplus.WebAuctionPlus
version: 3.0.2
author: lorenzop
website: http://webauctionplus.com/
depend: [Vault]
commands:
  wa:
    description: WebAuctionPlus
    usage: Use "/wa password [somepassword]" to set your password, then log into the WebAuction on the website.
permissions:
  wa.*:
    description: Gives access to all WebAuction commands
    default: false
    children:
      wa.use.mailbox: true
      wa.use.withdraw.money: true
      wa.use.deposit.money: true
      wa.announcer.receive: true
      wa.create.sign.deposit: true
      wa.create.sign.withdraw: true
      wa.create.sign.mailbox: true
      wa.create.sign.recent: true
      wa.create.sign.shout: true
      wa.password.create: true
      wa.password.change: true
      wa.canbuy: true
      wa.cansell: true
      wa.remove: true
      wa.webadmin: true
      wa.reload: true
  wa.use.*:
    description: Gives access to all WebAuction commands
    default: false
    children:
      wa.use.mailbox: true
      wa.use.withdraw.money: true
      wa.use.deposit.money: true
      wa.announcer.receive: true
      wa.password.create: true
      wa.password.change: true
      wa.canbuy: true
      wa.cansell: true
  wa.create.*:
    description: Gives access to all create and remove sign permissions
    default: false
    children:
      wa.create.sign.mailbox: true
      wa.create.sign.deposit: true
      wa.create.sign.withdraw: true
      wa.create.sign.recent: true
      wa.create.sign.shout: true
      wa.remove: true
  wa.password.*:
    description: Gives access to create an account or change password
    default: false
    children:
      wa.password.create: true
      wa.password.change: true
  wa.use.mailbox:
    description: Lets you use the mailbox
    default: true
  wa.use.withdraw.money:
    description: Lets you withdraw money from web account
    default: true
  wa.use.deposit.money:
    description: Lets you deposit money to web account
    default: true
  wa.announcer.receive:
    description: Let you see announcements in chat
    default: true
  wa.password.create:
    description: Lets you create a new account for the website
    default: true
  wa.password.change:
    description: Lets you change your password for the website
    default: true
  wa.canbuy:
    description: Lets you buy items on the website
    default: true
  wa.cansell:
    description: Lets you sell items on the website
    default: true
  wa.create.sign.mailbox:
    description: Lets you create mailbox signs
    default: op
  wa.create.sign.deposit:
    description: Lets you create money deposit points
    default: op
  wa.create.sign.withdraw:
    description: Lets you create money withdraw points
    default: op
  wa.create.sign.recent:
    description: Lets you create a sign to display recent auctions created
    default: op
  wa.create.sign.shout:
    description: Lets you create a sign to shout to all players nearby when a new auction is made
    default: op
  wa.remove:
    description: Lets you remove signs
    default: op
  wa.webadmin:
    description: Lets you change other peoples data via website
    default: op
  wa.reload:
    description: Reloads the WebAuctionPlus config.yml
    default: op